### ISSUE TITLE
Test suite fails (with older Mojolicious versions?)

### ISSUE THREAD

**Issue by eserte** [srchulo/Mojolicious-Plugin-CascadingConfig#1]
On some of my smoker systems:
```
#   Failed test 'production and development config files should load successfully'
#   at t/app_mode_optional.t line 13.
# died: Can't locate object method "child" via package "Mojo::Home" at /home/cpansand/.cpan/build/2019032201/Mojolicious-Plugin-CascadingConfig-0.01-rP_Pz7/blib/lib/Mojolicious/Plugin/CascadingConfig.pm line 35, <DATA> line 2231.

#   Failed test 'foo value from development config file'
#   at t/app_mode_optional.t line 15.
#          got: undef
#     expected: 'not_bar'

#   Failed test 'baz value from production config file'
#   at t/app_mode_optional.t line 16.
#     Structures begin differing at:
#          $got = undef
#     $expected = ARRAY(0x4676ad80)

#   Failed test 'music_dir value from production config file'
#   at t/app_mode_optional.t line 17.
#          got: undef
#     expected: 'music'
# Looks like you failed 4 tests of 4.
t/app_mode_optional.t ......... 
Dubious, test returned 4 (wstat 1024, 0x400)
Failed 4/4 subtests 
... (etc) ...
```

This seems to happen with older Mojolicious versions. Statistical analysis (theta=0 means "bad"):
```
****************************************************************
Regression 'mod:Mojolicious'
****************************************************************
Name           	       Theta	      StdErr	 T-stat
[0='const']    	      0.0000	      0.0000	   0.00
[1='eq_7.05']  	      0.0000	      0.0000	   0.00
[2='eq_7.18']  	      0.0000	      0.0000	   3.58
[3='eq_7.55']  	      1.0000	      0.0000	16109691382590100.00
[4='eq_8.10']  	      1.0000	      0.0000	16109691382590100.00
[5='eq_8.12']  	      1.0000	      0.0000	21092537195170552.00
[6='eq_8.13']  	      1.0000	      0.0000	22059103411727960.00

R^2= 1.000, N= 28, K= 7
****************************************************************
```

**Comment by srchulo** [comment]
Thanks for letting me know! What's a smoker system?

Seems like it probably is because of old Mojolicious versions. I may just need to set the minimum.

**Comment by eserte** [comment]
Smokers = systems dedicating for testing, in this case, CPAN modules.

Yes, setting the Mojolicious minimum to 7.55 would help here.

**Comment by srchulo** [comment]
It looks like 7.15 may be enough?

https://github.com/mojolicious/mojo/commit/0afb80bdc05b995b81a80a02af2c0ed52f3b4e3c
https://metacpan.org/source/SRI/Mojolicious-7.15/lib/Mojo/Home.pm

Did you figure out 7.55 was the right version, or did you just see it passing for that version?

**Comment by srchulo** [comment]
I bumped the required version to 7.15 here: 

https://metacpan.org/release/SRCHULO/Mojolicious-Plugin-CascadingConfig-0.02
https://github.com/srchulo/Mojolicious-Plugin-CascadingConfig/commit/a57ac57b80f7a2e6b9230199e448b25ccb8b58c1

I guess we'll see if the tests pass now.

**Comment by eserte** [comment]
> It looks like 7.15 may be enough?

No, as the statistical analysis above shows, it fails also with 7.18.

**Comment by srchulo** [comment]
Okay, I bumped the version to 7.55 here:

https://github.com/srchulo/Mojolicious-Plugin-CascadingConfig/commit/037c1873d52261869bb10bd9f4bcc7edf25bc350
https://metacpan.org/release/SRCHULO/Mojolicious-Plugin-CascadingConfig-0.03

**Comment by srchulo** [comment]
This seems to be fixed now. Thanks for letting me know!
